### ISSUE TITLE
Unable to unload lib_calebj

### ISSUE THREAD

**Issue by Kovaelin** [calebj/calebj-cogs#57] opened 2018-06-04 15:15 UTC
I've disable analytics, but your cog is causing conflicts with another one.

**Comment by calebj** [comment] 2018-06-11 14:19
It's not an actual cog file, so unloading normally won't work. This isn't a bug. As I said on Discord: if you're trying to do something, there's probably another way. Post more information on the conflict so I have something to work with, or I'll close this as invalid.

**Comment by calebj** [comment] 2018-06-14 15:33
I'll wait 24 hours for a response. If there isn't one, I'm closing this.

**Comment by Kovaelin** [comment] 2018-06-14 17:49
> It's not an actual cog file, so unloading normally won't work.

What is it, and why is it required if analytics are supposedly disabled?

**Comment by calebj** [comment] 2018-06-14 19:40
You can [read the code yourself](../blob/master/_analytics/analytics_core.py) to see what it does and how. The `GVAnalytics` cog is loaded through evaluation by whichever cog loads it first, then its `module` attribute is changed to detach it from that cog's module. `[p]unload` only looks for actual files in the `cogs/` folder. It stays loaded as a singleton so that opt-in works once and across all cogs, and so the interface doesn't have to check the JSON on the disk each time it wants to send an event.

**Comment by Stylite** [comment] 2018-06-14 20:43
So if a user opted out why wouldn't the analytics cog delete itself?

**Comment by calebj** [comment] 2018-06-14 21:36
Already answered:
> so the interface doesn't have to check the JSON on the disk each time it wants to send an event.

Hitting the disk is a relatively expensive operation, so doing it for each command would impact performance. The way it works now, unless the user opts in, the cog remains in memory and simply discards events instead of sending them.

Fire up Wireshark to check the traffic, or use the included script to strip the minified code from the cogs, if you like. Of course, if you have the skills to do those things, you probably have the knowledge to read the code and verify that raising questions was unwarranted.

I won't waste my time with any more questions in this thread that reading the code could answer just as easily. Both of you would already know the answers to your questions if you had actually bothered to read the code.

**Comment by Kovaelin** [comment] 2018-06-15 04:12
Wouldn't it be possible to not install `GVAnalytics` at all from the beginning? Seems to me that the answer is "yes". It also seems a bit evasive for you to just want to avoid these questions and call it a "waste" of time, to be honest.

**Comment by calebj** [comment] 2018-06-15 14:47
No, opening an issue claiming a conflict because you don't like something is being "evasive", and asking questions the code can answer *is* wasting my time. I already explained my design choices; if a better solution is so obvious to you, *make a PR*. I'll wait.

The full source code is published for anyone to read, and includes tools both to reproduce the minified form and to replace it in all cogs at once; the only thing I'm "avoiding" is your agenda. You want a witch-hunt over something that's provably a non-issue, not answers. Go away.

**Closed as completed by calebj** 2018-06-15 14:47 UTC
Labels: Type: Question
